name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            if [ ${{ github.event.pull_request.merged }} == 'false' ]; then
              echo "This PR was closed without merging. Exiting..."
              exit 0
            fi
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            publish_branch: gh-pages